export const supportedLanguages = [
    { language: 'Arabic', locale: 'ar' },
    { language: 'Armenian', locale: 'hy' },
    { language: 'Basque', locale: 'eu' },
    { language: 'Bengali', locale: 'bn' },
    { language: 'Catalan', locale: 'ca' },
    { language: 'Chinese ', locale: 'zh' },
    { language: 'Czech', locale: 'cs' },
    { language: 'Danish', locale: 'da' },
    { language: 'English', locale: 'en' },
    { language: 'Finnish', locale: 'fi' },
    { language: 'French', locale: 'fr' },
    { language: 'Galician', locale: 'gl' },
    { language: 'German', locale: 'de' },
    { language: 'Greek', locale: 'el' },
    { language: 'Hindi', locale: 'hi' },
    { language: 'Hungarian', locale: 'hu' },
    { language: 'Indonesian', locale: 'id' },
    { language: 'Irish', locale: 'ga' },
    { language: 'Italian', locale: 'it' },
    { language: 'Japanese', locale: 'ja' },
    { language: 'Korean', locale: 'ko' },
    { language: 'Lithuanian', locale: 'lt' },
    { language: 'Malay', locale: 'ms' },
    { language: 'Nepali', locale: 'ne' },
    { language: 'Norwegian', locale: 'nb' },
    { language: 'Persian ', locale: 'fa' },
    { language: 'Polish', locale: 'pl' },
    { language: 'Portuguese', locale: 'pt' },
    { language: 'Romanian', locale: 'ro' },
    { language: 'Russian', locale: 'ru' },
    { language: 'Serbian', locale: 'sr' },
    { language: 'Slovenian', locale: 'sl' },
    { language: 'Spanish', locale: 'es' },
    { language: 'Swedish', locale: 'sv' },
    { language: 'Tagalog', locale: 'tl' },
    { language: 'Tamil', locale: 'ta' },
    { language: 'Thai', locale: 'th' },
    { language: 'Turkish', locale: 'tr' },
    { language: 'Ukrainian', locale: 'uk' }
  ];